<a href="https://colab.research.google.com/github/soopertramp/Assignments/blob/main/9.3%20-%20NumPy%20Operations%20Assignment%20Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#### **Problem 1**

#### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Your code here

average = random_integers[:5, 2:4].mean()
print(f'The average of the asked columns is {average}')

The average of the asked columns is 286058.5


#### **Problem 2** 

#### In this problem, we are going to calculate distances between some pairs of points :

#### Measures of distances 
* #### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* #### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


#### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


#### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points

twoD_array = np.random.randint(5,20, size = (10,2))
twoD_array

array([[19, 12],
       [10, 16],
       [ 7, 12],
       [10, 19],
       [ 5,  9],
       [ 7,  7],
       [ 5, 14],
       [16,  6],
       [ 5,  8],
       [ 6,  8]])

In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair

def eucledian_distance(point1,point2):
    """Calculates and returns Eucledian Distance"""
    x1,y1=point1
    x2,y2=point2
    return round(((x2-x1)**2+(y2-y1)**2)**0.5,2)     
    
euclidean_distances=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(eucledian_distance(twoD_array[i],twoD_array[j]))
    euclidean_distances.append(np.asarray(inner_llist))
euclidean_distances = np.asarray(euclidean_distances)
print(euclidean_distances)

[[ 0.    9.85 12.   11.4  14.32 13.   14.14  6.71 14.56 13.6 ]
 [ 9.85  0.    5.    3.    8.6   9.49  5.39 11.66  9.43  8.94]
 [12.    5.    0.    7.62  3.61  5.    2.83 10.82  4.47  4.12]
 [11.4   3.    7.62  0.   11.18 12.37  7.07 14.32 12.08 11.7 ]
 [14.32  8.6   3.61 11.18  0.    2.83  5.   11.4   1.    1.41]
 [13.    9.49  5.   12.37  2.83  0.    7.28  9.06  2.24  1.41]
 [14.14  5.39  2.83  7.07  5.    7.28  0.   13.6   6.    6.08]
 [ 6.71 11.66 10.82 14.32 11.4   9.06 13.6   0.   11.18 10.2 ]
 [14.56  9.43  4.47 12.08  1.    2.24  6.   11.18  0.    1.  ]
 [13.6   8.94  4.12 11.7   1.41  1.41  6.08 10.2   1.    0.  ]]


In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.

def manhattan_distance(point1,point2):
    """Calculates and returns manhattan_distance"""
    x1,y1=point1
    x2,y2=point2
    return round((abs(x1 - x2) + abs(y1 - y2)),2)     
    
manhattan_distance=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(eucledian_distance(twoD_array[i],twoD_array[j]))
    manhattan_distance.append(np.asarray(inner_llist))
manhattan_distance = np.asarray(manhattan_distance)
print(manhattan_distance)



[[ 0.    9.85 12.   11.4  14.32 13.   14.14  6.71 14.56 13.6 ]
 [ 9.85  0.    5.    3.    8.6   9.49  5.39 11.66  9.43  8.94]
 [12.    5.    0.    7.62  3.61  5.    2.83 10.82  4.47  4.12]
 [11.4   3.    7.62  0.   11.18 12.37  7.07 14.32 12.08 11.7 ]
 [14.32  8.6   3.61 11.18  0.    2.83  5.   11.4   1.    1.41]
 [13.    9.49  5.   12.37  2.83  0.    7.28  9.06  2.24  1.41]
 [14.14  5.39  2.83  7.07  5.    7.28  0.   13.6   6.    6.08]
 [ 6.71 11.66 10.82 14.32 11.4   9.06 13.6   0.   11.18 10.2 ]
 [14.56  9.43  4.47 12.08  1.    2.24  6.   11.18  0.    1.  ]
 [13.6   8.94  4.12 11.7   1.41  1.41  6.08 10.2   1.    0.  ]]


#### Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here

nearest_points_manhattan=[]
for ind,arr in enumerate(manhattan_distance + np.identity(10)*1000):
    nearest_points_manhattan.append((twoD_array[ind],twoD_array[arr.argmin()]))         
    
print(nearest_points_manhattan)

nearest_points_euclidean=[]
for ind,arr in enumerate(euclidean_distances+np.identity(10)*1000):
    nearest_points_euclidean.append((twoD_array[ind],twoD_array[arr.argmin()]))        

print(nearest_points_euclidean)

[(array([19, 12]), array([16,  6])), (array([10, 16]), array([10, 19])), (array([ 7, 12]), array([ 5, 14])), (array([10, 19]), array([10, 16])), (array([5, 9]), array([5, 8])), (array([7, 7]), array([6, 8])), (array([ 5, 14]), array([ 7, 12])), (array([16,  6]), array([19, 12])), (array([5, 8]), array([5, 9])), (array([6, 8]), array([5, 8]))]
[(array([19, 12]), array([16,  6])), (array([10, 16]), array([10, 19])), (array([ 7, 12]), array([ 5, 14])), (array([10, 19]), array([10, 16])), (array([5, 9]), array([5, 8])), (array([7, 7]), array([6, 8])), (array([ 5, 14]), array([ 7, 12])), (array([16,  6]), array([19, 12])), (array([5, 8]), array([5, 9])), (array([6, 8]), array([5, 8]))]


#### **Problem 3**

#### Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..

contiguous_list = []

extract = np.random.randint(10,50, size = (10,10))
print(extract)

for row in range(0,8):
  for col in range(0,8):
    contiguous_list.append(extract[row:row + 3, col:col + 3])

contiguous_array = np.asarray(contiguous_list)

print(contiguous_array)

[[11 37 43 42 41 12 32 20 39 35]
 [27 13 11 11 25 43 43 21 21 23]
 [47 46 32 27 19 39 13 40 48 38]
 [34 11 11 38 26 35 45 20 19 14]
 [38 26 44 10 40 24 11 24 11 46]
 [10 13 17 42 34 45 40 20 39 33]
 [49 40 47 22 45 44 28 36 41 25]
 [35 28 24 48 13 36 47 22 11 15]
 [20 46 13 32 15 21 29 45 44 49]
 [21 10 15 46 11 36 31 26 23 25]]
[[[11 37 43]
  [27 13 11]
  [47 46 32]]

 [[37 43 42]
  [13 11 11]
  [46 32 27]]

 [[43 42 41]
  [11 11 25]
  [32 27 19]]

 [[42 41 12]
  [11 25 43]
  [27 19 39]]

 [[41 12 32]
  [25 43 43]
  [19 39 13]]

 [[12 32 20]
  [43 43 21]
  [39 13 40]]

 [[32 20 39]
  [43 21 21]
  [13 40 48]]

 [[20 39 35]
  [21 21 23]
  [40 48 38]]

 [[27 13 11]
  [47 46 32]
  [34 11 11]]

 [[13 11 11]
  [46 32 27]
  [11 11 38]]

 [[11 11 25]
  [32 27 19]
  [11 38 26]]

 [[11 25 43]
  [27 19 39]
  [38 26 35]]

 [[25 43 43]
  [19 39 13]
  [26 35 45]]

 [[43 43 21]
  [39 13 40]
  [35 45 20]]

 [[43 21 21]
  [13 40 48]
  [45 20 19]]

 [[21 21 23]
  [40 48 38]
  [20 19 14]]

 [[47 46 32]


#### **Problem 4** 

#### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below

def get_nearest_value(elem,array):
    """Return the nearest value in the given array for given input"""
    nearest_value = array.flat[np.abs(array - elem).argmin()]                   
    return nearest_value
array=np.random.randint(10,500, size=(1, 15))
print(array)

[[308 417  12 473 130  85 294 443  93 476 375 353 380 484  90]]


In [ ]:
ele=int(input("Enter the element for which you want to find the nearest value for "))
print(f"Nearest point to {ele} is {get_nearest_value(ele,array)}")

Enter the element for which you want to find the nearest value for 2
Nearest point to 2 is 12
